_wandb:
    value:
        cli_version: 0.21.4
        e:
            6ma6tawjol28kdcla62do0ykp2a8cb7i:
                codePath: train_tbyt.py
                codePathLocal: train_tbyt.py
                cpu_count: 96
                cpu_count_logical: 96
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "53660876800"
                        used: "19822776320"
                email: suhither@gmail.com
                executable: /n/home13/chloe00/miniforge3/envs/vla/bin/python
                git:
                    commit: 454881fb52d538a259cec3746b3140d2243d8b50
                    remote: git@github.com:gatmiry/sort-llm.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-e49d7e17-ee41-1678-26c8-b48bbf2aa0c5
                host: holygpu8a13101.rc.fas.harvard.edu
                memory:
                    total: "1622574518272"
                os: Linux-4.18.0-553.44.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /n/holylfs06/LABS/sham_lab/Users/chloe00/sort-llm/./train_tbyt.py
                python: CPython 3.11.14
                root: /n/holylfs06/LABS/sham_lab/Users/chloe00/sort-llm
                slurm:
                    cluster_name: odyssey
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: kempner_grads
                    job_cpus_per_node: "1"
                    job_end_time: "1767527952"
                    job_gid: "5142"
                    job_gpus: "1"
                    job_id: "54118691"
                    job_name: interactive
                    job_nodelist: holygpu8a13101
                    job_num_nodes: "1"
                    job_partition: kempner_h100
                    job_qos: normal
                    job_start_time: "1767506352"
                    job_uid: "65790"
                    job_user: chloe00
                    jobid: "54118691"
                    launch_node_ipaddr: 10.31.21.18
                    localid: "0"
                    mem_per_node: "204800"
                    mpi_type: none
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: holygpu8a13101
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "8686"
                    pty_win_col: "330"
                    pty_win_row: "12"
                    script_context: prolog_task
                    srun_comm_host: 10.31.21.18
                    srun_comm_port: "10650"
                    step_id: "4294967290"
                    step_launcher_port: "10650"
                    step_nodelist: holygpu8a13101
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    stepmgr: holygpu8a13101
                    submit_dir: /n/holylfs06/LABS/sham_lab/Users/chloe00
                    submit_host: holylogin08.rc.fas.harvard.edu
                    task_pid: "4058955"
                    tasks_per_node: "1"
                    topology_addr: main.holyoke.holyndr.holygpu8a13101
                    topology_addr_pattern: switch.switch.switch.node
                startedAt: "2026-01-04T06:03:46.332374Z"
                writerId: 6ma6tawjol28kdcla62do0ykp2a8cb7i
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
            "4": 3.11.14
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
