_wandb:
    value:
        cli_version: 0.21.4
        e:
            2sbmypas50w9w48pjbq9m8d82ogiha1g:
                codePath: train_tbyt.py
                codePathLocal: train_tbyt.py
                cpu_count: 96
                cpu_count_logical: 96
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "53660876800"
                        used: "20041535488"
                email: suhither@gmail.com
                executable: /n/home13/chloe00/miniforge3/envs/vla/bin/python
                git:
                    commit: 75c8ef509b48f3d9eb49afc8b919601c24df2eef
                    remote: git@github.com:gatmiry/sort-llm.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-f982d4df-1830-935e-8843-8f75a1a6de6e
                host: holygpu8a11503.rc.fas.harvard.edu
                memory:
                    total: "1622517022720"
                os: Linux-4.18.0-553.44.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /n/holylfs06/LABS/sham_lab/Users/chloe00/sort-llm/./train_tbyt.py
                python: CPython 3.11.14
                root: /n/holylfs06/LABS/sham_lab/Users/chloe00/sort-llm
                slurm:
                    cluster_name: odyssey
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: kempner_grads
                    job_cpus_per_node: "1"
                    job_end_time: "1767675612"
                    job_gid: "5142"
                    job_gpus: "0"
                    job_id: "54308788"
                    job_name: interactive
                    job_nodelist: holygpu8a11503
                    job_num_nodes: "1"
                    job_partition: kempner_h100
                    job_qos: normal
                    job_start_time: "1767654012"
                    job_uid: "65790"
                    job_user: chloe00
                    jobid: "54308788"
                    launch_node_ipaddr: 10.31.21.16
                    localid: "0"
                    mem_per_node: "204800"
                    mpi_type: none
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: holygpu8a11503
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "11751"
                    pty_win_col: "125"
                    pty_win_row: "13"
                    script_context: prolog_task
                    srun_comm_host: 10.31.21.16
                    srun_comm_port: "10268"
                    step_id: "4294967290"
                    step_launcher_port: "10268"
                    step_nodelist: holygpu8a11503
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    stepmgr: holygpu8a11503
                    submit_dir: /n/holylfs06/LABS/sham_lab/Users/chloe00
                    submit_host: holylogin06.rc.fas.harvard.edu
                    task_pid: "2489114"
                    tasks_per_node: "1"
                    topology_addr: main.holyoke.holyndr.holygpu8a11503
                    topology_addr_pattern: switch.switch.switch.node
                startedAt: "2026-01-05T23:01:55.598576Z"
                writerId: 2sbmypas50w9w48pjbq9m8d82ogiha1g
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
            "4": 3.11.14
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
